/**
 * @description 4个子配置，cli配置|通用配置|主题配置|网络配置导出
 */
import { cliConfig } from './cli.config'
import { netConfig } from './net.config'
import { settingConfig } from './setting.config'
import { themeConfig } from './theme.config'

const config: { [key: string]: any } = {
  ...cliConfig,
  ...netConfig,
  ...settingConfig,
  ...themeConfig,
}

export default config

export const {
  abbreviation,
  assetsDir,
  authentication,
  base,
  chunkSizeWarningLimit,
  color,
  colorWeakness,
  columnStyle,
  contentType,
  copyright,
  cssCodeSplit,
  debounce,
  defaultOpeneds,
  errorLog,
  fixedHeader,
  foldSidebar,
  i18n,
  isCatchedTabs,
  isFollow,
  isHashRouterMode,
  keepAliveMaxNum,
  layout,
  loadingText,
  localEnabled,
  loginInterception,
  loginRSA,
  logo,
  menuWidth,
  messageDuration,
  messageName,
  minify,
  open,
  openFirstMenu,
  outDir,
  outputHash,
  pageTransition,
  port,
  prodEnabled,
  pwa,
  radius,
  recordRoute,
  reportCompressedSize,
  rolesControl,
  routesWhiteList,
  showColorPicker,
  showDark,
  showFooter,
  showFullScreen,
  showLanguage,
  showLock,
  showNotice,
  showProgressBar,
  showRefresh,
  showSearch,
  showTabs,
  showTabsIcon,
  showTheme,
  showThemeSetting,
  statusName,
  storage,
  successCode,
  supportVisit,
  tabsBarStyle,
  themeName,
  timeout,
  title,
  titleReverse,
  titleSeparator,
  tokenName,
  tokenTableName,
  uniqueOpened,
} = config
